#sudo: false
dist: trusty
language: cpp
os:
  - linux
compiler:
  - gcc
before_install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [[ $CXX = g++ ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5 # not sure why we needed this
  packages:
    - gcc-4.9
    - g++-4.9
#language: c

#compiler:
#  - gcc
#os: linux
#dist: trusty
env:
   - GTEST_DIR=/home/travis/build/Eiwanger/ESP/googletest/googletest
install:
 - sudo apt-get -qq update
 - pwd
 - ls -al
 - git clone https://github.com/google/googletest.git
 - sudo apt-get install -y valgrind
 - ls -al
 - ls -la ${GTEST_DIR} 
 - sudo apt-get install libgtest-dev
 - sudo apt-get install cmake 
 - cd /usr/src/gtest 
 - ls -al
 - sudo cmake .
 - sudo make
 - sudo mv libg* /usr/lib/
 - cd /usr/lib/
 - ls -la
 - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"
 - cd ESP/Code_4_linked_list/
 - g++ -c -isystem ${GTEST_DIR}/include -I ${GTEST_DIR} Gtest_main.c 
 - g++ -isystem ${GTEST_DIR}/include -I${GTEST_DIR} -pthread -c ${GTEST_DIR}/home/travis/build/Eiwanger/src/gtest-all.cc
 -  ar -rv libgtest.a gtest-all.o

 - g++ -c -isystem ${GTEST_DIR}/include -I ${GTEST_DIR} linked_list_test_case.c -o linked_list_test_case.o
 - g++ -Wall -c -g linked_list.c -o linked_list_test.o
 - g++ -I ${GTEST_DIR}/include -pthread linked_list_test_case.o Gtest_main.o libgtest.a linked_list_test.o -g -o unit_test 

#before_scrip    - make test
#script:
#    - ./unit_test
branches:
  only:
    - master
    - student
    - additional
    - bidir
notifications:
  recipients:
    - jukka.matila@vamk.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
