language: c
compiler:
  - gcc
os: linux
dist: trusty
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install cmake
 - pwd
 - ls -la
 - cd /home/travis/build/Eiwanger/ESP/
 - git clone https://github.com/google/googletest.git 
 - ls -la
 - cd /home/travis/build/Eiwanger/ESP/googletest/googletest
 - sudo cmake .
# - sudo make
 - cd /home/travis/build/Eiwanger/ESP/ESP/Code_4_linked_list/
before_script:
    - bash scripts/travisMake 
script:
    - ./unit_test
branches:
  only:
    - master
    - student
    - bidir
notifications:
  recipients:
    - jukka.matila@vamk.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
