language: c
compiler:
  - gcc
os: linux
dist: trusty
before_install:
 - sudo apt-get -qq update
# - cd $
 - git clone https://github.com/google/googletest.git ~/travis/build/Eiwanger/ESP
 - cd ~/travis/build/Eiwanger/ESP/googletest/googletest
 - sudo cmake .
 - sudo make
 - cd ~/travis/build/Eiwanger/ESP/ESP/Code_4_linked_list/
before_script:
    - make test
script:
    - ./test
branches:
  only:
    - master
    - student
    - bidir
notifications:
  recipients:
    - jukka.matila@vamk.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
