language: c
compiler:
  - gcc
os: linux
dist: trusty
before_install:
 - sudo apt-get -qq update
 - pwd
 - ls -al
 - git clone https://github.com/google/googletest.git
 - sudo apt-get install -y valgrind
 - ls -al
 - cd /usr/src/
 - ls -al
 - cd /usr/src/gtest 
 - sudo cmake .
 - sudo make
 - sudo mv libg* /usr/lib/
 - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"

before_script:
    - make test
script:
    - ./test
branches:
  only:
    - master
    - student
    - additional
    - bidir
notifications:
  recipients:
    - jukka.matila@vamk.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
