language: c
compiler:
  - gcc
os: linux
dist: trusty
env:
 - GTEST_DIR=~/home/travis/build/Eiwanger/googletest/googletest

before_install:
 - sudo apt-get -qq update
 - pwd
 - ls -al
 - git clone https://github.com/google/googletest.git
 - sudo apt-get install -y valgrind
 - ls -al
 - ls -la ~/home/travis/build/Eiwanger/googletest/
 - sudo apt-get install libgtest-dev
 - sudo apt-get install cmake 
 - cd /usr/src/gtest 
 - ls -al
 - sudo cmake .
 - sudo make
 - sudo mv libg* /usr/lib/
 - cd /usr/lib/
 - ls -la
 - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"
 - cd ESP/Code_4_linked_list/
 - g++ -c -isystem ${GTEST_DIR}/include -I ${GTEST_DIR} Gtest_main.c 
 - g++ -isystem ${GTEST_DIR}/include -I${GTEST_DIR} -pthread -c ${GTEST_DIR}/home/travis/build/Eiwanger/src/gtest-all.cc
 -  ar -rv libgtest.a gtest-all.o

 - g++ -c -isystem ${GTEST_DIR}/include -I ${GTEST_DIR} linked_list_test_case.c -o linked_list_test_case.o
 - g++ -Wall -c -g linked_list.c -o linked_list_test.o
 - g++ -I ${GTEST_DIR}/include -pthread linked_list_test_case.o Gtest_main.o libgtest.a linked_list_test.o -g -o unit_test 

#before_scrip    - make test
#script:
#    - ./unit_test
branches:
  only:
    - master
    - student
    - additional
    - bidir
notifications:
  recipients:
    - jukka.matila@vamk.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
