language: c
compiler:
  - gcc
os: linux
dist: trusty
before_install:
 - sudo apt-get -qq update
 - pwd
 - ls -al
 - git clone https://github.com/google/googletest.git
 - sudo apt-get install -y valgrind
 - ls -al
 - cd /usr/src/
 - sudo apt-get install libgtest-dev
 - sudo apt-get install cmake 
 - cd /usr/src/gtest 
 - ls -al
 - sudo cmake .
 - sudo make
 - sudo mv libg* /usr/lib/
 - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"
 - cd ESP/Code_4_linked_list/
 - export GTEST_DIR=~/home/travis/Studium/WS18_fin/prg_c/googletest/googletest
 - g++ -c -isystem /home/travis/Studium/WS18_fin/prg_c/googletest/googletest/include -I/home/travis/Studium/WS18_fin/prg_c/googletest/googletest Gtest_main.c 
 - g++ -c -isystem /home/travis/Studium/WS18_fin/prg_c/googletest/googletest/include -I/home/travis/Studium/WS18_fin/prg_c/googletest/googletest linked_list_test_case.c -o linked_list_test_case.o
 - g++ -Wall -c -g linked_list.c -o linked_list_test.o
 - g++ -I /home/travis/Studium/WS18_fin/prg_c/googletest/googletest/include -pthread linked_list_test_case.o Gtest_main.o libgtest.a linked_list_test.o -g -o unit_test 


#before_scrip    - make test
#script:
#    - ./unit_test
branches:
  only:
    - master
    - student
    - additional
    - bidir
notifications:
  recipients:
    - jukka.matila@vamk.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
