#sudo: false
dist: trusty
language: cpp
os:
- linux
compiler:
- gcc
#language: c

#compiler:
#  - gcc
#os: linux
#dist: trusty
env:
- GTEST_DIR=/home/travis/build/Eiwanger/ESP/googletest/googletest
before_install:

- sudo apt-get -qq update
- pwd
- git clone https://github.com/google/googletest.git
- sudo apt-get install -y valgrind
- ls -la ${GTEST_DIR} 
- sudo apt-get install libgtest-dev
- sudo apt-get install cmake 
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-4.9 -y
- cd /usr/src/gtest 
- sudo cmake .
- sudo make
- sudo mv libg* /usr/lib/
- cd /usr/lib/
- ls -la
- which valgrind
- cd "${TRAVIS_BUILD_DIR}"

before_script:
 bash scripts/travisMake.sh
script:
    - ./unit_test
branches:
only:
- master
- student
- additional
- bidir
notifications:
recipients:
- jukka.matila@vamk.fi
email:
on_success: always
on_failure: change
rvm:
- 9.00
